####################################################################################################
# LLM Presets
####################################################################################################

[llm.presets]

llm_for_swe = { llm_handle = "smart_llm", temperature = 0.1 }
