####################################################################################################
# LLM Deck overrides
####################################################################################################

[llm_choice_overrides]
for_text = "disabled"
for_object = "disabled"

[llm_presets]
llm_for_large_text = { llm_handle = "gemini-2.5-pro", temperature = 0.1 }
llm_for_swe = { llm_handle = "claude-4-sonnet", temperature = 0.1 }