[pipelex_inference]
endpoint = "https://inference.pipelex.com/v1"
api_key = "${PIPELEX_INFERENCE_API_KEY}"

[blackboxai]
enabled = true
endpoint = "https://api.blackbox.ai/v1"
api_key = "${BLACKBOX_API_KEY}"

[openai]
enabled = true
api_key = "${OPENAI_API_KEY}"

[azure_openai]
enabled = true
endpoint = "${AZURE_API_BASE}"
api_key = "${AZURE_API_KEY}"
api_version = "${AZURE_API_VERSION}"

[anthropic]
enabled = true
api_key = "${ANTHROPIC_API_KEY}"
claude_4_tokens_limit = 8192

[ollama]
enabled = true
endpoint = "http://localhost:11434/v1"

[xai]
enabled = true
endpoint = "https://api.x.ai/v1"
api_key = "${XAI_API_KEY}"

[bedrock]
enabled = true
aws_region = "${AWS_REGION}"

[vertexai]
enabled = true
gcp_project_id = "${GCP_PROJECT_ID}"
gcp_location = "${GCP_LOCATION}"
gcp_credentials_file_path = "${GCP_CREDENTIALS_FILE_PATH}"

[mistral]
enabled = true
api_key = "${MISTRAL_API_KEY}"

